services:
  app-service:
    image: johnsoto718/app-service # specify name of image on Docker Hub
    restart: "always" # automatically restart container when server crashes
    environment: # set up environment variables
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP} # Use localhost as the default value
    ports:
      - "8000:8000" # expose port 8000 so that applications outside the container can connect to it 
    depends_on: # only run app-service after auth-service has started
      auth-service:
        condition: service_started

  auth-service:
    image: johnsoto718/auth-service
    restart: "always" # automatically restart container when server crashes
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      MYSQL_SERVER_URL: ${MYSQL_SERVER_URL}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: rust_auth_service
      MYSQL_USER: john
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST_NAME: redis
    ports:
      - "3000:3000" # expose port 3000 so that applications outside the container can connect to it 

    # depends_on:
    #  - db

  # db:
  #   image: mysql:8.0
  #   container_name: mysql-db
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: rust_auth_service
  #     MYSQL_USER: john
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   ports:
  #       - "3307:3306"
  #   volumes:
  #       - db:/var/lib/mysql
  
  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  db:
    driver: local